### ISSUE TITLE
Tika

### ISSUE THREAD

**Issue by thrako** [ilambrev/SoftUni_Software_Engineering_Program#1]
Здравей,

Търсих те снощи след лекцията, но не се появяваш във ФБ групите. Ето как ползвам Tika в моя проект, може би трябва да се полира малко, но никак не е сложно:
https://github.com/thrako/receptaria/blob/main/src/main/java/dev/thrako/receptaria/utility/PhotoExtensionValidator.java
Поздрави,
Траян

**Comment by ilambrev** [comment]
Здравей, благодаря за информацията. Нямам Фейсбук акаунт. Ползвам само Discord сървъра на курса, но и там не съм влизал от известно време.

Иначе ще ми е много интересно да разгледам как се ползва тази библиотека. Видях, че си добавил в твоя проект следното дипендънси за да ползваш библиотеката:

`<dependency>`
`    <groupId>org.apache.tika</groupId>`
`    <artifactId>tika-core</artifactId>`
`    <version>2.6.0</version>`
`</dependency>`

Предполагам, че това е достатъчно.

**Comment by thrako** [comment]
Да. Напълно достатъчно е. Аз съм си направил статични методи, защото не мисля, че този обект трябва да пази някакъв state, но предполагам, че можеш да expose-неш Tika като Bean, или пък твой си валидатор като Bean и да си го викаш, където ти е необходим.
П.С. И аз не харесвам ФБ, ползвам го основно, заради СофтУни групите. Социализирането също  е важно, не само програмирането. :)

Sent from Trayan's phone.
________________________________
